# Generated by Django 5.2.3 on 2025-06-20 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquirente',
            fields=[
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amministratore',
            fields=[
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('IdAutore', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donatore',
            fields=[
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('nome_genere', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descrizione', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBN', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=100, null=True)),
                ('editore', models.CharField(max_length=100, null=True)),
                ('anno_pubblicazione', models.CharField(max_length=100, null=True)),
                ('edizione', models.CharField(max_length=100, null=True)),
                ('lingua', models.CharField(max_length=100, null=True)),
                ('copertina_rigida', models.CharField(max_length=100, null=True)),
                ('materia', models.CharField(max_length=100, null=True)),
                ('classe_scolastica', models.CharField(max_length=100, null=True)),
                ('data_pubblicazione', models.DateField(null=True)),
                ('quantita_disponibili', models.CharField(max_length=100, null=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donazioni.autore')),
                ('genere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donazioni.genere')),
            ],
        ),
        migrations.CreateModel(
            name='Donazione',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=100, null=True)),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donazioni.donatore')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Donazioni.libro')),
            ],
        ),
    ]
