# Generated by Django 5.2.3 on 2025-06-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amministratore',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='quantita_disponibili',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LibroAcquistato',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('data_acquisto', models.DateField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donazioni.acquirente')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donazioni.libro')),
            ],
        ),
    ]
