# Generated by Django 5.2.3 on 2025-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donazioni', '0003_alter_libro_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='autore',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
