# Generated by Django 5.2.3 on 2025-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donazioni', '0004_autore_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='classe_scolastica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
