# Generated by Django 5.2.3 on 2025-06-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donazioni', '0006_rename_idautore_autore_username'),
        ('Donazioni', '0006_rename_idautore_to_username'),
    ]

    operations = [
    ]
